export const START_LOAD_TOP_TRACKS = 'START_LOAD_TOP_TRACKS';
export const LOADED_TOP_TRACKS = 'LOADED_TOP_TRACKS';
export const ERROR_TOP_TRACKS = 'ERROR_TOP_TRACKS';

export const START_LOAD_ARTIST_INFO = 'START_LOAD_ARTIST_INFO';
export const LOADED_ARTIST_INFO = 'LOADED_ARTIST_INFO';
export const ERROR_ARTIST_INFO = 'ERROR_ARTIST_INFO';

export const START_LOAD_SEARCH = 'START_LOAD_SEARCH';
export const LOADED_SEARCH = 'LOADED_SEARCH';
export const ERROR_SEARCH = 'ERROR_SEARCH';
